# Generated by Django 2.0.5 on 2018-05-22 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='work',
            name='description',
        ),
        migrations.AddField(
            model_name='workdesc',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_api.Work'),
        ),
    ]
