# Generated by Django 2.0.5 on 2018-05-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0004_auto_20180524_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillset',
            name='framework',
        ),
        migrations.RemoveField(
            model_name='skillset',
            name='language',
        ),
        migrations.RemoveField(
            model_name='skillset',
            name='tool',
        ),
        migrations.AddField(
            model_name='skillset',
            name='skill',
            field=models.CharField(choices=[('Languages', 'Languages'), ('Frameworks', 'Frameworks'), ('Tolls', 'Tools')], default='Proficient', max_length=20),
        ),
    ]
