# Generated by Django 2.0.5 on 2018-05-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0006_auto_20180524_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
    ]
