# Generated by Django 2.0.5 on 2018-05-23 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0002_auto_20180522_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdesc',
            name='job_description',
            field=models.CharField(max_length=750),
        ),
        migrations.AlterField(
            model_name='workdesc',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workdesc', to='portfolio_api.Work'),
        ),
    ]
