# Generated by Django 2.0.5 on 2018-05-24 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0003_auto_20180523_0335'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
                ('framework', models.CharField(max_length=100)),
                ('tool', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SkillType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('image', models.URLField(max_length=500)),
                ('proficieny', models.CharField(choices=[('Proficient', 'Proficient'), ('Intermediate', 'Intermediate'), ('Beginning', 'Beginning')], default='Proficient', max_length=20)),
                ('skillset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skilltype', to='portfolio_api.SkillSet')),
            ],
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
