# Generated by Django 2.0.5 on 2018-05-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0007_auto_20180524_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='certificate',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='education',
            name='major',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='work',
            name='end_date',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='work',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
    ]
