# Generated by Django 2.0.5 on 2018-05-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0008_auto_20180524_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='minor',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
