# Generated by Django 2.0.5 on 2018-06-10 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0011_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='degree',
        ),
        migrations.AddField(
            model_name='certificate',
            name='end_date',
            field=models.DateField(default=None, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='start_date',
            field=models.DateField(default=None, verbose_name='Start Date'),
        ),
    ]
